language: python
python:
  - "3.10"
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
matrix:
 include:
   - python: 3.4
     dist: trusty
   - python: 2.7
     before_install:
       - pip install -U mock
       - pip install -U pytest
# command to install dependencies
install:
  - pip install -r requirements.txt && pip install -e .
# command to run tests
script:
  - pytest
